swagger: '2.0'
info:
  description: This document describes the endpoints for chucknorris.io.
  version: 1.0.0
  title: CHUCKNORRIS.IO
  termsOfService: 'https://api.chucknorris.io/privacy'
  contact:
    email: daniel.zabotti@parmais.com.br
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
#host: api.chucknorris.io
basePath: /api
tags:
- name: facts
  description: Chucknorris Facts
  externalDocs:
    description: Find out more
    url: 'http://chucknorris.io'
schemes:
- http
paths:
  /jokes/random:
    get:
      tags:
      - facts
      summary: Retrieve a random Chuck Norris joke in JSON format.
      description: You may set the category parameter in order to filter the facts by it
      x-swagger-router-controller: Facts
      operationId: randomFact
      produces:
      - application/json
      parameters:
      - name: category
        in: query
        description: ''
        required: false
        type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Fact'
  /jokes/categories:
    get:
      tags:
      - facts
      summary: Retrieve a list of available categories.
      x-swagger-router-controller: Facts
      operationId: listCategories
      produces:
      - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              type: string
  /jokes/search:
    get:
      tags:
      - facts
      summary: Free text search.
      description: You may set the category parameter in order to filter the facts by it
      x-swagger-router-controller: Facts
      operationId: search
      produces:
      - application/json
      parameters:
      - name: query
        in: query
        description: ''
        required: true
        type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/SearchResult'
definitions:
  SearchResult:
    type: object
    properties:
      total:
        type: number
      result:
        type: array
        items:
          $ref: '#/definitions/Fact'
  Fact:
    type: object
    properties:
      category:
        type: array
        items:
          type: string
      icon_url:
        type: string
      id:
        type: string
      url:
        type: string
      value:
        type: string
externalDocs:
  description: Want to now more about Par Mais?
  url: 'http://parmais.com.br'
